# dev/docker-compose.yml
version: '3'
services:
  python:
    image: python:3.10
    volumes:
      - ./../:/project
    working_dir: /project
    command: sleep infinity  # Keeps the container running for interactive use