# .github/workflows/test.yml
name: Test

# Can customize when the automation is run
on: [push, workflow_dispatch]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
          cache: pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests and generate JUnit report
        run: pytest --junitxml=results/test-results.xml

      - name: Install TestMo
      - run: npm install --no-save @testmo/testmo-cli

      - name: Submit results to TestMo
      - run: |
          npx testmo automation:run:submit \
            --instance "$TESTMO_URL" \
            --project-id 1 \
            --name "Python test run" \
            --source "unit-tests" \
            --results results/*.xml \
            -- python -m unittest discover
        env:
          TESTMO_URL: ${{ secrets.TESTMO_URL }}
          TESTMO_TOKEN: ${{ secrets.TESTMO_TOKEN }}
        

